/*
 * @Description: 文件描述
 * @Author: Liu.YF
 * @Date: 2022-07-06 11:30:28
 * @LastEditTime: 2022-07-18 16:33:51
 * @Custom_string_obkoro1_copyright: Copyright (c) ${now_year} by HL, All Rights Reserved. 
 */


#include "lvgl/lvgl.h"

LV_IMG_DECLARE(bg_pic)

//temp
LV_IMG_DECLARE(control_cycle_blue_a)
LV_IMG_DECLARE(control_cycle_blue_b)
LV_IMG_DECLARE(control_cycle_blue_c)
LV_IMG_DECLARE(control_cycle_blue_d)
LV_IMG_DECLARE(control_cycle_blue_e)
LV_IMG_DECLARE(control_cycle_blue_f)


LV_IMG_DECLARE(control_cycle_green_a)
LV_IMG_DECLARE(control_cycle_green_b)
LV_IMG_DECLARE(control_cycle_green_c)
LV_IMG_DECLARE(control_cycle_green_d)
LV_IMG_DECLARE(control_cycle_green_e)
LV_IMG_DECLARE(control_cycle_green_f)


LV_IMG_DECLARE(control_cycle_orange_a)
LV_IMG_DECLARE(control_cycle_orange_b)
LV_IMG_DECLARE(control_cycle_orange_c)
LV_IMG_DECLARE(control_cycle_orange_d)
LV_IMG_DECLARE(control_cycle_orange_e)
LV_IMG_DECLARE(control_cycle_orange_f)


LV_IMG_DECLARE(tabbar_bg_blue)
LV_IMG_DECLARE(tabbar_bg_green)
LV_IMG_DECLARE(tabbar_bg_orange)




LV_IMG_DECLARE(nav_icon_switch)
LV_IMG_DECLARE(banner_bg)
LV_IMG_DECLARE(bottom_upward_bg_03)


//wind_ctrl
LV_IMG_DECLARE(wind_speed_1)
LV_IMG_DECLARE(wind_speed_2)
LV_IMG_DECLARE(wind_speed_3)
LV_IMG_DECLARE(wind_speed_4)
LV_IMG_DECLARE(wind_speed_5)
LV_IMG_DECLARE(wind_speed_6)
LV_IMG_DECLARE(wind_speed_7)
LV_IMG_DECLARE(tab_wind_speed_icon_auto_sel)
LV_IMG_DECLARE(tab_wind_speed_icon_auto_nor)



//mode
LV_IMG_DECLARE(tab_icon_mode_auto_nor)
LV_IMG_DECLARE(tab_icon_mode_auto_pre)
LV_IMG_DECLARE(tab_icon_mode_cool_nor)
LV_IMG_DECLARE(tab_icon_mode_cool_pre)
LV_IMG_DECLARE(tab_icon_mode_dehumidification_nor)
LV_IMG_DECLARE(tab_icon_mode_dehumidification_pre)
LV_IMG_DECLARE(tab_icon_mode_heat_nor)
LV_IMG_DECLARE(tab_icon_mode_heat_pre)
LV_IMG_DECLARE(tab_icon_mode_wind_nor)
LV_IMG_DECLARE(tab_icon_mode_wind_pre)


//tabbar
LV_IMG_DECLARE(bottom_icon_heat1)
LV_IMG_DECLARE(bottom_icon_heat2)
LV_IMG_DECLARE(sleep_diy_pop_icon_cool)
LV_IMG_DECLARE(sleep_diy_pop_icon_cool2)
LV_IMG_DECLARE(tab_icon_auto_green)
LV_IMG_DECLARE(tab_icon_auto_nor)
LV_IMG_DECLARE(tab_icon_cool_blue)
LV_IMG_DECLARE(tab_icon_cool_nor)
LV_IMG_DECLARE(tab_icon_heat_nor)
LV_IMG_DECLARE(tab_icon_heat_orange)
LV_IMG_DECLARE(tab_icon_humidification_blue)
LV_IMG_DECLARE(tab_icon_humidification_nor)
LV_IMG_DECLARE(tab_icon_wind_green)
LV_IMG_DECLARE(tab_icon_wind_nor)

//anim
LV_IMG_DECLARE(light_animation)
LV_IMG_DECLARE(tab_snow1)
LV_IMG_DECLARE(tab_snow2)
LV_IMG_DECLARE(tab_snow3)
LV_IMG_DECLARE(tab_snow4)
LV_IMG_DECLARE(water)
LV_IMG_DECLARE(windmill_fan_big)
LV_IMG_DECLARE(windmill_fan_samll)
LV_IMG_DECLARE(windmill_rod_big)
LV_IMG_DECLARE(windmill_rod_small)


//show
LV_IMG_DECLARE(aircondition_control_electric_heating)
LV_IMG_DECLARE(aircondition_control_fan1)
LV_IMG_DECLARE(aircondition_control_fan2)
LV_IMG_DECLARE(aircondition_control_fan3)
LV_IMG_DECLARE(aircondition_control_fan4)
LV_IMG_DECLARE(aircondition_control_fan5)
LV_IMG_DECLARE(aircondition_control_fan6)
LV_IMG_DECLARE(aircondition_control_fan7)
LV_IMG_DECLARE(aircondition_control_icon_auto)
LV_IMG_DECLARE(aircondition_control_icon_auto2)
LV_IMG_DECLARE(aircondition_control_icon_cool)
LV_IMG_DECLARE(aircondition_control_icon_dehumidification)
LV_IMG_DECLARE(aircondition_control_icon_eco)
LV_IMG_DECLARE(aircondition_control_icon_heat)
LV_IMG_DECLARE(aircondition_control_icon_wind)
LV_IMG_DECLARE(aircondition_control_icon_wind_up_down)
LV_IMG_DECLARE(aircondition_control_sleep)
LV_IMG_DECLARE(aircondition_control_wind_left_right)


LV_IMG_DECLARE(tab_icon_eco_nor)
LV_IMG_DECLARE(tab_icon_sleep_nor)
LV_IMG_DECLARE(tab_icon_wind_direction_left_right_nor)
LV_IMG_DECLARE(tab_icon_wind_direction_up_down_nor)

//wind_speed
LV_IMG_DECLARE(cool_tab_icon_eco_sel)
LV_IMG_DECLARE(cool_tab_icon_sleep_sel)
LV_IMG_DECLARE(cool_tab_icon_wind_direction_left_right_sel)
LV_IMG_DECLARE(cool_tab_icon_wind_direction_up_down_sel)
LV_IMG_DECLARE(tab_icon_wind_auto_nor_blue)
LV_IMG_DECLARE(tab_icon_wind_auto_sel_blue)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan1)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan2)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan3)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan4)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan5)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan6)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_blue_fan7)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan1)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan2)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan3)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan4)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan5)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan6)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_blue_fan7)


// green bg
LV_IMG_DECLARE(tab_icon_wind_auto_nor_green)
LV_IMG_DECLARE(tab_icon_wind_auto_sel_green)
LV_IMG_DECLARE(wind_tab_icon_eco_sel)
LV_IMG_DECLARE(wind_tab_icon_sleep_sel)
LV_IMG_DECLARE(wind_tab_icon_wind_direction_left_right_sel)
LV_IMG_DECLARE(wind_tab_icon_wind_direction_up_down_sel)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan1)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan2)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan3)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan4)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan5)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan6)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_green_fan7)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan1)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan2)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan3)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan4)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan5)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan6)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_green_fan7)




// orange bg
LV_IMG_DECLARE(heat_tab_icon_eco_sel)
LV_IMG_DECLARE(heat_tab_icon_sleep_sel)
LV_IMG_DECLARE(heat_tab_icon_wind_direction_left_right_sel)
LV_IMG_DECLARE(heat_tab_icon_wind_direction_up_down_sel)
LV_IMG_DECLARE(tab_icon_wind_auto_nor_orange)
LV_IMG_DECLARE(tab_icon_wind_auto_sel_orange)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan1)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan2)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan3)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan4)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan5)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan6)
LV_IMG_DECLARE(tab_icon_wind_speed_nor_orange_fan7)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan1)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan2)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan3)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan4)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan5)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan6)
LV_IMG_DECLARE(tab_icon_wind_speed_sel_orange_fan7)


